### ISSUE TITLE
Code Cleanup Master Issue

### ISSUE THREAD

**Issue by James-Oswald** [RAIRLab/Peirce-My-Heart#241]
Comment any code cleanup issues here with checkboxes.
- [ ] : Redo Tools to be imported with just their module names then access handlers with `Tool.handler`
- [x] : Replace Linked List with regular JS List  
- [x] setTool in index.ts should not be exported. This was likened to creating methods in the main() of a Java class. Figure out some fix!
- [x] Get rid of magic numbers in index.ts regarding enums (~line 250)
- [ ] Helper function for currentProofTree in ProofTools 
>               If we need this exact block of code in every single proof mode tool it should be turned into a helper function.

- [ ] Nothing from draw tools should be imported by proof tools, should all be moved to a shared tools utils file or folder with multiple files in the src folder. 

_Originally posted by @James-Oswald in https://github.com/RAIRLab/Peirce-My-Heart/pull/287#discussion_r1416093641_

**Comment by AnushaTiwari5** [comment]
> * [ ]  Get rid of magic numbers in index.ts regarding enums (~line 250)
in pr #286
